version: '3'
services:
  web:
    image: clementlefevredocker/urban-soccer:latest
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
        - .:/code
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
    command: ["gunicorn", "-w", "4", "app:app", "--bind", "0.0.0.0:5000"]